### ISSUE TITLE
Invalid reference 'AgentDetails'

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/gsim-raml-schema#28]
Tried to convert raml to json by using raml-to-jsonschema but failed
`java -jar ../raml-to-jsonschema/target/raml-to-jsonschema-0.15-SNAPSHOT.jar jsonschemas/ schemas/`

```
Invalid reference 'AgentDetails'
/types/EnumeratedValueDomain/properties/agentDetails?/type
Invalid reference 'AgentDetails'
FILE: schemas\EnumeratedValueDomain.raml
java.lang.RuntimeException: Unable to create RAML Specification
        at no.ssb.raml.ramlhandler.RAMLJsonSchema04DefinitionBuilder.build(RAMLJsonSchema04DefinitionBuilder.java:39)
        at no.ssb.raml.ramlhandler.RamlSchemaParser.convertRamlToJsonSchema04Format(RamlSchemaParser.java:27)
        at no.ssb.raml.RamltoJsonSchemaConverter.convertRamlToJsonSchema(RamltoJsonSchemaConverter.java:142)
        at no.ssb.raml.RamltoJsonSchemaConverter.lambda$parseDirectoryFiles$0(RamltoJsonSchemaConverter.java:120)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at no.ssb.raml.RamltoJsonSchemaConverter.parseDirectoryFiles(RamltoJsonSchemaConverter.java:116)
        at no.ssb.raml.RamltoJsonSchemaConverter.convertSchemas(RamltoJsonSchemaConverter.java:95)
        at no.ssb.raml.RamltoJsonSchemaConverter.main(RamltoJsonSchemaConverter.java:38)
```

**Comment by alina-lapina** [comment]
my bad, local problems. sorry
